# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.55.0"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    ENV["CRASHLYTICS_API_TOKEN"] = "6cb0cc9d48b1339629f655b453be597013aa0899"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "90385b5b011ee156cdf8ab4852a4a84b86a811f5d4c91dc09b8b00b745607a07"
  end

  desc "テスト実行"
  lane :test do
    scan
  end

  desc “アルファ版をFabricCrashlyticsにデプロイ"
  lane :beta do
    gym(scheme: 'TastingNote-Coffee', export_method: 'development')

    # crashlytics にipaをアップロードする処理を追加
    crashlytics(api_token: ENV["CRASHLYTICS_API_TOKEN"],
         build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
               emails: ["junic.maruyama@gmail.com"],
               groups: ["developers"],
                notes: "Distributed with fastlane",
        notifications: true)
  end

  desc “ベータ版をTestFlightにデプロイ"
  lane :release do
    gym # Build your app - more options available
    pilot
    # deliver(force: true)
  end

  after_all do |lane|
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end